apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: tracing-server
  name: tracing-server
spec:
  ports:
  - name: "9411"
    port: 9411
    targetPort: 9411
  selector:
    io.kompose.service: tracing-server
status:
  loadBalancer: {}
