###############################################################################
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

ui:
  image: saturnism/spring-boot-helloworld-ui
  ports:
    - "8080:8080"
  links:
    - helloworldservice
    - guestbookservice
    - redis

helloworldservice:
  image: saturnism/spring-boot-helloworld-service

guestbookservice:
  image: saturnism/guestbook-service
  ports:
    - "8888:8080"
  links:
    - mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: yourpassword
    MYSQL_DATABASE: app

redis:
  image: redis
