apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: guestbook-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: helloworld-ui
          servicePort: 80
